---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# chordgen

The goal of chordgen is to generate random chords using R

## Installation

You can install chordgen from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("r-music/chordgen")
```

## Example

This is a basic example:

```{r chords, fig.width=8, fig.height=4}
library(chordgen)

chordgen(20, 
         n_notes = 3:4, 
         octave = 0, 
         transpose = 0, 
         triad_types = 1:5,
         invert = FALSE,
         add_lyric = TRUE) %>% 
  plot()
```

## Shiny app

Check out the shiny app

```{r, eval=FALSE}
app <- system.file("chordgen/app.R", package = "chordgen")
shiny::runApp(app)
```

Or run directly from github (after installing `chordgen`, of course)

```{r, eval=FALSE}
shiny::runGitHub("chordgen", "r-music", subdir="inst/chordgen/")
```


